export enum Permission {
  USER_CREATE = 'USER_CREATE',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',
  USER_VIEW = 'USER_VIEW',
  EMPLOYEE_VIEW = 'EMPLOYEE_VIEW',
  EMPLOYEE_UPDATE = 'EMPLOYEE_UPDATE',
  ATTENDANCE_APPROVE = 'ATTENDANCE_APPROVE',
  PERFORMANCE_VIEW = 'PERFORMANCE_VIEW',
  REPORT_EXPORT = 'REPORT_EXPORT',
  PAYROLL_VIEW = 'PAYROLL_VIEW',
  SYSTEM_CONFIGURATION = 'SYSTEM_CONFIGURATION',
}
