import { DashboardChartConfig } from './chart.types';

export const ROLE_CHART_CONFIGS: Record<string, DashboardChartConfig[]> = {
  ADMIN: [
    {
      id: 'admin_headcount_dept',
      title: 'Headcount & Departmental Distribution',
      subtitle: 'Active staff breakdown across departments',
      type: 'stacked-bar',
      xKey: 'department',
      realtime: true,
      series: [
        { key: 'fullTime', label: 'Full Time', color: '#10b981' },
        { key: 'contract', label: 'Contract', color: '#06b6d4' },
        { key: 'intern', label: 'Intern', color: '#8b5cf6' },
      ],
    },
    {
      id: 'admin_workforce_growth',
      title: 'Workforce Growth & Attrition',
      subtitle: 'Net headcount changes over time',
      type: 'area',
      xKey: 'month',
      realtime: true,
      series: [
        { key: 'joined', label: 'New Hires', color: '#10b981' },
        { key: 'exited', label: 'Exits', color: '#f43f5e' },
      ],
    },
    {
      id: 'admin_payroll_expense',
      title: 'Monthly Payroll Expense Trend',
      subtitle: 'Total gross salary and statutory disbursements',
      type: 'line',
      xKey: 'month',
      realtime: true,
      series: [
        { key: 'grossSalary', label: 'Gross Payroll', color: '#3b82f6', unit: '₹' },
        { key: 'netPayout', label: 'Net Payout', color: '#10b981', unit: '₹' },
      ],
    },
    {
      id: 'admin_attendance_rate',
      title: 'Global Attendance & Presenteeism',
      subtitle: 'Daily organization-wide present vs absent percentage',
      type: 'composed',
      xKey: 'date',
      realtime: true,
      series: [
        { key: 'presentPct', label: 'Present %', type: 'area', color: '#10b981', unit: '%' },
        { key: 'latePct', label: 'Late %', type: 'line', color: '#f59e0b', unit: '%' },
      ],
    },
    {
      id: 'admin_dept_overtime',
      title: 'Department-Wise Overtime Hours',
      subtitle: 'Cumulative OT hours billed this month',
      type: 'bar',
      xKey: 'department',
      realtime: true,
      series: [
        { key: 'otHours', label: 'OT Hours', color: '#8b5cf6', unit: 'hrs' },
      ],
    },
    {
      id: 'admin_login_devices',
      title: 'Device & Access Breakdown',
      subtitle: 'Active user login channel distribution',
      type: 'donut',
      xKey: 'device',
      realtime: true,
      series: [
        { key: 'count', label: 'Sessions' },
      ],
    },
    {
      id: 'admin_audit_activity',
      title: 'System Audit Activity & Alerts',
      subtitle: 'Daily security events and configuration changes',
      type: 'line',
      xKey: 'date',
      realtime: true,
      series: [
        { key: 'events', label: 'Audit Events', color: '#6366f1' },
        { key: 'alerts', label: 'Security Alerts', color: '#f43f5e' },
      ],
    },
    {
      id: 'admin_work_location',
      title: 'Shift & Location Share',
      subtitle: 'Office vs Remote vs Field breakdown',
      type: 'pie',
      xKey: 'mode',
      realtime: true,
      series: [
        { key: 'count', label: 'Employees' },
      ],
    },
  ],

  HR: [
    {
      id: 'hr_onboarding_pipeline',
      title: 'Employee Onboarding & Offboarding',
      subtitle: 'Monthly candidate joining and exit pipeline',
      type: 'bar',
      xKey: 'month',
      realtime: true,
      series: [
        { key: 'onboarded', label: 'Onboarded', color: '#10b981' },
        { key: 'offboarded', label: 'Offboarded', color: '#f43f5e' },
      ],
    },
    {
      id: 'hr_leave_distribution',
      title: 'Leave Request Distribution',
      subtitle: 'Paid vs Sick vs Casual leave usage',
      type: 'donut',
      xKey: 'type',
      realtime: true,
      series: [
        { key: 'days', label: 'Days' },
      ],
    },
    {
      id: 'hr_attrition_risk',
      title: 'Departmental Attrition Risk',
      subtitle: 'Predicted & historic department turnover rate',
      type: 'area',
      xKey: 'department',
      realtime: true,
      series: [
        { key: 'turnoverRate', label: 'Turnover Rate', color: '#f59e0b', unit: '%' },
      ],
    },
    {
      id: 'hr_diversity_ratio',
      title: 'Workforce Diversity & Inclusion',
      subtitle: 'Gender diversity representation across organization',
      type: 'pie',
      xKey: 'gender',
      realtime: true,
      series: [
        { key: 'count', label: 'Count' },
      ],
    },
    {
      id: 'hr_performance_reviews',
      title: 'Performance Review Completion Status',
      subtitle: 'Appraisal cycle completion breakdown',
      type: 'stacked-bar',
      xKey: 'quarter',
      realtime: true,
      series: [
        { key: 'completed', label: 'Completed', color: '#10b981' },
        { key: 'pending', label: 'Pending', color: '#f59e0b' },
        { key: 'overdue', label: 'Overdue', color: '#f43f5e' },
      ],
    },
    {
      id: 'hr_statutory_claims',
      title: 'Monthly Statutory & Compliance Claims',
      subtitle: 'PF, ESI, and LWF claim trends',
      type: 'line',
      xKey: 'month',
      realtime: true,
      series: [
        { key: 'pfClaim', label: 'PF Claims', color: '#06b6d4', unit: '₹' },
        { key: 'esiClaim', label: 'ESI Claims', color: '#8b5cf6', unit: '₹' },
      ],
    },
    {
      id: 'hr_time_to_hire',
      title: 'Average Time-to-Hire Trend',
      subtitle: 'Days from requisition to offer acceptance',
      type: 'line',
      xKey: 'month',
      realtime: true,
      series: [
        { key: 'avgDays', label: 'Avg Days', color: '#3b82f6', unit: 'days' },
      ],
    },
    {
      id: 'hr_absenteeism_pattern',
      title: 'Absenteeism & Sick Leave Pattern',
      subtitle: 'Monthly unplanned absences trend',
      type: 'composed',
      xKey: 'month',
      realtime: true,
      series: [
        { key: 'unplannedDays', label: 'Unplanned Days', type: 'bar', color: '#f43f5e' },
        { key: 'sickLeavePct', label: 'Sick Leave %', type: 'line', color: '#f59e0b', unit: '%' },
      ],
    },
  ],

  MANAGER: [
    {
      id: 'mgr_team_attendance',
      title: 'Team Attendance & Shift Adherence',
      subtitle: 'Daily present vs late vs absent team count',
      type: 'composed',
      xKey: 'date',
      realtime: true,
      series: [
        { key: 'present', label: 'Present', type: 'bar', color: '#10b981' },
        { key: 'late', label: 'Late', type: 'line', color: '#f59e0b' },
        { key: 'absent', label: 'Absent', type: 'bar', color: '#f43f5e' },
      ],
    },
    {
      id: 'mgr_project_allocation',
      title: 'Team Project Workload Allocation',
      subtitle: 'Hours assigned across active project streams',
      type: 'bar',
      xKey: 'project',
      realtime: true,
      series: [
        { key: 'allocatedHours', label: 'Allocated Hours', color: '#3b82f6', unit: 'hrs' },
        { key: 'loggedHours', label: 'Logged Hours', color: '#10b981', unit: 'hrs' },
      ],
    },
    {
      id: 'mgr_leave_coverage',
      title: 'Team Leave Balance & Coverage',
      subtitle: 'Upcoming scheduled leaves for team members',
      type: 'stacked-bar',
      xKey: 'member',
      realtime: true,
      series: [
        { key: 'casualRemaining', label: 'Casual Left', color: '#06b6d4', unit: 'days' },
        { key: 'sickRemaining', label: 'Sick Left', color: '#f59e0b', unit: 'days' },
        { key: 'earnedRemaining', label: 'Earned Left', color: '#10b981', unit: 'days' },
      ],
    },
    {
      id: 'mgr_overtime_trend',
      title: 'Team Overtime vs Regular Hours',
      subtitle: 'Weekly total workload split',
      type: 'area',
      xKey: 'week',
      realtime: true,
      series: [
        { key: 'regularHours', label: 'Regular Hours', color: '#10b981', unit: 'hrs' },
        { key: 'otHours', label: 'OT Hours', color: '#8b5cf6', unit: 'hrs' },
      ],
    },
    {
      id: 'mgr_sprint_performance',
      title: 'Sprint Deliverables & Velocity',
      subtitle: 'Completed vs Target story points',
      type: 'line',
      xKey: 'sprint',
      realtime: true,
      series: [
        { key: 'targetPoints', label: 'Target Points', color: '#6366f1' },
        { key: 'completedPoints', label: 'Completed Points', color: '#10b981' },
      ],
    },
    {
      id: 'mgr_task_status',
      title: 'Task Completion & Delay Metrics',
      subtitle: 'Breakdown of current team tasks state',
      type: 'pie',
      xKey: 'status',
      realtime: true,
      series: [
        { key: 'count', label: 'Tasks' },
      ],
    },
    {
      id: 'mgr_shift_coverage',
      title: 'Shift Schedule Roster Coverage',
      subtitle: 'Day vs Night vs Rotational shift distribution',
      type: 'donut',
      xKey: 'shift',
      realtime: true,
      series: [
        { key: 'count', label: 'Staff' },
      ],
    },
    {
      id: 'mgr_remote_pattern',
      title: 'Remote vs Office Working Pattern',
      subtitle: 'Team work location preferences',
      type: 'donut',
      xKey: 'mode',
      realtime: true,
      series: [
        { key: 'count', label: 'Days' },
      ],
    },
  ],

  TEAM_LEAD: [
    {
      id: 'tl_checkin_timings',
      title: 'Daily Team Check-in Timings',
      subtitle: 'Punctuality pattern over current week',
      type: 'line',
      xKey: 'day',
      realtime: true,
      series: [
        { key: 'avgCheckinHour', label: 'Avg Check-in Time', color: '#10b981', unit: 'AM' },
      ],
    },
    {
      id: 'tl_active_backlog',
      title: 'Active Task Status & Backlog',
      subtitle: 'Sprint task progress breakdown',
      type: 'donut',
      xKey: 'status',
      realtime: true,
      series: [
        { key: 'count', label: 'Items' },
      ],
    },
    {
      id: 'tl_velocity_burndown',
      title: 'Sprint Velocity & Burn-Down',
      subtitle: 'Remaining sprint effort burn-down',
      type: 'area',
      xKey: 'day',
      realtime: true,
      series: [
        { key: 'idealRemaining', label: 'Ideal', color: '#cbd5e1' },
        { key: 'actualRemaining', label: 'Actual', color: '#3b82f6' },
      ],
    },
    {
      id: 'tl_code_reviews',
      title: 'Peer Code Review & PR Velocity',
      subtitle: 'Open vs Merged pull requests',
      type: 'bar',
      xKey: 'member',
      realtime: true,
      series: [
        { key: 'openedPRs', label: 'Opened PRs', color: '#f59e0b' },
        { key: 'mergedPRs', label: 'Merged PRs', color: '#10b981' },
      ],
    },
    {
      id: 'tl_weekly_overtime',
      title: 'Weekly Overtime Distribution',
      subtitle: 'Team OT hours logged per weekday',
      type: 'bar',
      xKey: 'day',
      realtime: true,
      series: [
        { key: 'otHours', label: 'OT Hours', color: '#8b5cf6', unit: 'hrs' },
      ],
    },
    {
      id: 'tl_availability_calendar',
      title: 'Team Availability Status',
      subtitle: 'Available vs On Leave vs Offsite',
      type: 'pie',
      xKey: 'status',
      realtime: true,
      series: [
        { key: 'count', label: 'Members' },
      ],
    },
    {
      id: 'tl_incident_resolution',
      title: 'Incident Response & Resolution',
      subtitle: 'Average time to fix critical issues',
      type: 'line',
      xKey: 'week',
      realtime: true,
      series: [
        { key: 'avgHoursToResolve', label: 'Avg Resolution Time', color: '#f43f5e', unit: 'hrs' },
      ],
    },
    {
      id: 'tl_skill_assignment',
      title: 'Project Skill Assignment',
      subtitle: 'Technology stack allocations across team',
      type: 'stacked-bar',
      xKey: 'skill',
      realtime: true,
      series: [
        { key: 'assignedCount', label: 'Assigned Members', color: '#06b6d4' },
      ],
    },
  ],

  EMPLOYEE: [
    {
      id: 'emp_personal_attendance',
      title: 'Personal Attendance & Punctuality',
      subtitle: 'Monthly worked hours vs target hours',
      type: 'composed',
      xKey: 'date',
      realtime: true,
      series: [
        { key: 'workedHours', label: 'Worked Hours', type: 'bar', color: '#10b981', unit: 'hrs' },
        { key: 'targetHours', label: 'Target', type: 'line', color: '#3b82f6', unit: 'hrs' },
      ],
    },
    {
      id: 'emp_salary_trend',
      title: 'Monthly Net Payout Trend',
      subtitle: 'Net salary credit history over last 6 months',
      type: 'area',
      xKey: 'month',
      realtime: true,
      series: [
        { key: 'netSalary', label: 'Net Salary', color: '#10b981', unit: '₹' },
      ],
    },
    {
      id: 'emp_leave_entitlement',
      title: 'Leave Entitlement vs Balance',
      subtitle: 'Remaining quota across leave types',
      type: 'bar',
      xKey: 'leaveType',
      realtime: true,
      series: [
        { key: 'totalQuota', label: 'Total Quota', color: '#cbd5e1', unit: 'days' },
        { key: 'remaining', label: 'Remaining', color: '#06b6d4', unit: 'days' },
      ],
    },
    {
      id: 'emp_weekly_hours',
      title: 'Weekly Project Hours Logged',
      subtitle: 'Timesheet log breakdown per project',
      type: 'stacked-bar',
      xKey: 'day',
      realtime: true,
      series: [
        { key: 'projectA', label: 'Project Alpha', color: '#10b981', unit: 'hrs' },
        { key: 'projectB', label: 'Project Beta', color: '#3b82f6', unit: 'hrs' },
      ],
    },
    {
      id: 'emp_overtime_logged',
      title: 'Overtime Hours Logged',
      subtitle: 'Approved extra working hours',
      type: 'line',
      xKey: 'month',
      realtime: true,
      series: [
        { key: 'approvedOtHours', label: 'Approved OT', color: '#8b5cf6', unit: 'hrs' },
      ],
    },
    {
      id: 'emp_goal_progression',
      title: 'Performance & KPI Goals Progress',
      subtitle: 'Quarterly objective completion %',
      type: 'line',
      xKey: 'quarter',
      realtime: true,
      series: [
        { key: 'progressPct', label: 'Goal Completion %', color: '#f59e0b', unit: '%' },
      ],
    },
    {
      id: 'emp_checkin_punctuality',
      title: 'Shift Adherence & Punctuality',
      subtitle: 'On-time vs Late check-in ratio',
      type: 'donut',
      xKey: 'status',
      realtime: true,
      series: [
        { key: 'count', label: 'Days' },
      ],
    },
    {
      id: 'emp_tax_deductions',
      title: 'Tax Deduction & Statutory Savings',
      subtitle: 'Annual tax breakdown and savings',
      type: 'pie',
      xKey: 'category',
      realtime: true,
      series: [
        { key: 'amount', label: 'Amount', unit: '₹' },
      ],
    },
  ],
};
